### ISSUE TITLE
Sporadic lambda timeouts after migration to "datadog-lambda-extension"

### ISSUE THREAD

**Issue by hrist0stoichev** [DataDog/datadog-lambda-extension#191]
Hello! We were using the lambda forwarder for a long time and recently migrated to using the extension for sending logs to Datadog. I'm not 100% sure that this is due to the extension but we've been seeing sporadic timeouts for some of our lambda functions. I'll attach a few examples and try to explain what's wrong with them.

<img width="1534" alt="image" src="https://github.com/DataDog/datadog-lambda-extension/assets/6693671/d0c29464-a2b0-4120-bb32-b31187697589">
Starting simple, here are the logs for 1 particular execution. Note the following things

1. There are no logs whatsoever even though we expect to see some logs.
2. The runtime duration is negative.
3. The post runtime duration is huge. This is a function with 6s timeout.
4. The timestamps indicate that only ~300ms have passed.

<img width="1606" alt="image" src="https://github.com/DataDog/datadog-lambda-extension/assets/6693671/1163216c-5cec-4c41-94d9-db24ef26d3e2">

1. Runtime duration is negative
2. Post runtime duration is huge.
3. A lot of "double logging"
4. The logs prior to the START log indicate that this is a cold start but there is no Init Duration in the REPORT log.
5. "Invalid trace id" logs

<img width="1175" alt="image" src="https://github.com/DataDog/datadog-lambda-extension/assets/6693671/7ea976a3-4104-4f1a-ab73-f1642d0aa5a4">
Here actually the timeout is real and is indeed caused by the function being slow. The runtime duration and the post runtime durations look fine but note:

1. The function actually timed out all 3 times (1 when trigger + 2 from the automatic async retry), however, there is only 1 log for the timeout. It looks like the other 2 executions were successful but they weren't (actually the third execution is what made me think "wait, why we haven't stopped after the second one?" and then I realized that all 3 have timed out).
2. A very strange consequence of START -> REPORT -> START -> END -> REPORT -> START -> END
3. Timestamps are wrong. First execution correctly shows ~15m but the next two are showing 2-3 minutes of execution when in fact the functions were timing out after 15 minutes (pretty sure about that since they were hitting an infinite loop)

All in all, as said before, I'm not 100% sure that it's all caused by the extension but there's definitely something wrong going on with the logs. The examples I provided are from different functions and different times. It feels like there's some issue in sending logs to Datadog which causes our functions to time out and drop logs. Do you think that's possible?

**Comment by alexgallotta** [comment]
Thanks for reporting this!
It seems this issue might require a deeper analysis. Could you please file a ticket in https://help.datadoghq.com/hc/en-us/requests/new so we can follow the standard process?

**Comment by joel-eroad** [comment]
We are facing a similar kind of issue with Lambda timing out without even running the actual code. As you can see from the below log line, the Runtime Duration is 0 ms and Post Runtime Duration  is 0 ms, the actual code never got executed. 

```REPORT RequestId: dfcebe0d-66cc-4f40-a110-01c339fd97b6	Duration: 901730.40 ms	Runtime Duration: 0.00 ms	Post Runtime Duration: 0.00 ms	Billed Duration: 900000 ms	Memory Size: 2048 MB	Max Memory Used: 246 MB ```

We tried upgrading the Datadog AWS Lambda extension to the latest version (57) but still seeing those Lambda timeouts. When we remove the extension from the Lambda code and re-run, we no longer see those timeouts. 

Any update on this issue?

**Comment by steve-lebleu** [comment]
I encounter the same issue, quite hard to debug.  All permissions seems correct, role, secrets, etc... Just the forwarder fall in timeout. Anyone has more information about the question ?

**Comment by steve-lebleu** [comment]
> I encounter the same issue, quite hard to debug. All permissions seems correct, role, secrets, etc... Just the forwarder fall in timeout. Anyone has more information about the question ?

Fixed on my side using the cloudformation template instead of the manual setup. By the way the issue was coming from the access to the secret manager arn, also using the stack provided by the cloudformation.

**Comment by mlh758** [comment]
We're seeing a similar issue with the lambda extension. Post runtime duration can run up to the full 30 second timeout we have configured versus ~100ms to send a response. This is the only extension we have on our lambdas.

![image](https://github.com/user-attachments/assets/774cbf99-cf7f-4dad-8680-c1fcee06014d)

**Comment by hghotra** [comment]
Can everyone try the newest version of the extension and if they're still encountering the same issue, then please open a support request using https://help.datadoghq.com/hc/en-us/requests/new and someone from the engineering team will take a deeper look into it. 

@mlh758 @joel-eroad @hrist0stoichev

**Comment by ajohnston1219** [comment]
We are also having this issue. We had this issue initially with lambdas that had 128MB memory, and were recommended to increase this to 256MB. This solved the issue for a while, but now we are seeing the same behavior and had to increase the memory to 512MB. This fixed it for a few days, but again we are seeing the timeouts, so if this is memory related, its a memory leak and not just overhead. It is hard to determine what the cause is because, as people here have mentioned already, there are no logs indicating any issue. I have opened an issue via the help.datadoghq.com link shared above, but still wanted to mention here that this seems to be an ongoing issue.

**Comment by ajohnston1219** [comment]
After speaking with support, we turned on debug logs via the `DD_LOG_LEVEL` environment variable. Here are the logs that we received for one of our timeouts:

```csv
timestamp,message
1727361705215,"[AWS Parameters and Secrets Lambda Extension] 2024/09/26 14:41:45 PARAMETERS_SECRETS_EXTENSION_LOG_LEVEL is not present. Log level set to info.
"
1727361705216,"[AWS Parameters and Secrets Lambda Extension] 2024/09/26 14:41:45 INFO Systems Manager Parameter Store and Secrets Manager Lambda Extension 1.0.103
"
1727361705216,"[AWS Parameters and Secrets Lambda Extension] 2024/09/26 14:41:45 INFO Serving on port 2773
"
1727361705859,"2024-09-26 14:41:45 UTC | DD_EXTENSION | DEBUG | Datadog extension version : 57|Datadog environment variables: DD_API_KEY_SECRET_ARN=***|DD_CAPTURE_LAMBDA_PAYLOAD=false|DD_COLD_START_TRACING=false|DD_ENV=prod|DD_FLUSH_TO_LOG=false|DD_LAMBDA_HANDLER=index.handler|DD_LOGS_INJECTION=false|DD_LOG_LEVEL=debug|DD_MERGE_XRAY_TRACES=false|DD_PROFILING_ENABLED=false|DD_REMOTE_CONFIGURATION_ENABLED=false|DD_SERVERLESS_APPSEC_ENABLED=false|DD_SERVERLESS_LOGS_ENABLED=true|DD_SITE=datadoghq.com|DD_TAGS=git.commit.sha:""***********************************"",git.repository_url:********|DD_TRACE_ENABLED=false|
"
1727361705875,"2024-09-26 14:41:45 UTC | DD_EXTENSION | DEBUG | No config file detected, using environment variable based configuration only
"
1727361705875,"2024-09-26 14:41:45 UTC | DD_EXTENSION | DEBUG | 'use_proxy_for_cloud_metadata' is enabled: adding cloud provider URL to the no_proxy list
"
1727361705875,"2024-09-26 14:41:45 UTC | DD_EXTENSION | DEBUG | FIPS mode is disabled
"
1727361705875,"2024-09-26 14:41:45 UTC | DD_EXTENSION | INFO | 0 Features detected from environment:
"
1727361705875,"2024-09-26 14:41:45 UTC | DD_EXTENSION | DEBUG | Retrieving ALADDIN_FIREBASE_SECRET_ARN=************* from secrets manager
"
1727361705875,"2024-09-26 14:41:45 UTC | DD_EXTENSION | DEBUG | Found ************* value, trying to use it.
"
1727361706144,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | Retrieving DD_API_KEY_SECRET_ARN=************ from secrets manager
"
1727361706144,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | Found *********** value, trying to use it.
"
1727361706183,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | Retrieving OHD_FIREBASE_SECRET_ARN=************ from secrets manager
"
1727361706183,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | Found *************** value, trying to use it.
"
1727361706221,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | Starting daemon to receive messages from runtime...
"
1727361706239,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | Using a SyncForwarder with a 5s timeout
"
1727361706279,"2024-09-26 14:41:46 UTC | DD_EXTENSION | INFO | Retry queue storage on disk is disabled
"
1727361706335,"2024-09-26 14:41:46 UTC | DD_EXTENSION | INFO | Creating TimeSampler #0
"
1727361706335,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | 'telemetry.dogstatsd.aggregator_channel_latency_buckets' is empty, falling back to default values
"
1727361706335,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | 'telemetry.dogstatsd.listeners_latency_buckets' is empty, falling back to default values
"
1727361706335,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | 'telemetry.dogstatsd.listeners_channel_latency_buckets' is empty, falling back to default values
"
1727361706335,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | dogstatsd-udp: 127.0.0.1:8125 successfully initialized
"
1727361706335,"2024-09-26 14:41:46 UTC | DD_EXTENSION | INFO | Dogstatsd workers and pipelines count:  2  workers,  1  pipelines
"
1727361706335,"2024-09-26 14:41:46 UTC | DD_EXTENSION | INFO | Dogstatsd configured to run with 2 workers and 1 pipelines
"
1727361706335,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | DogStatsD will run 2 workers
"
1727361706335,"2024-09-26 14:41:46 UTC | DD_EXTENSION | INFO | Dogstatsd workers and pipelines count:  2  workers,  1  pipelines
"
1727361706335,"2024-09-26 14:41:46 UTC | DD_EXTENSION | INFO | Dogstatsd configured to run with 2 workers and 1 pipelines
"
1727361706335,"2024-09-26 14:41:46 UTC | DD_EXTENSION | INFO | Unable to initialize cgroup provider (cgroups not mounted?), err: unable to detect cgroup version from detected mount points: map[]
"
1727361706335,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | Metrics collector: system went into PermaFail, removed from candidates
"
1727361706335,"2024-09-26 14:41:46 UTC | DD_EXTENSION | INFO | Dogstatsd workers and pipelines count:  2  workers,  1  pipelines
"
1727361706335,"2024-09-26 14:41:46 UTC | DD_EXTENSION | INFO | Dogstatsd configured to run with 2 workers and 1 pipelines
"
1727361706335,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | appsec: security monitoring is not enabled: DD_SERVERLESS_APPSEC_ENABLED is not set to true
"
1727361706335,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | Forwarder started
"
1727361706335,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | Demultiplexer started
"
1727361706336,"2024-09-26 14:41:46 UTC | DD_EXTENSION | INFO | dogstatsd-udp: starting to listen on 127.0.0.1:8125
"
1727361706336,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | No config file detected, using environment variable based configuration only
"
1727361706336,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | 'use_proxy_for_cloud_metadata' is enabled: adding cloud provider URL to the no_proxy list
"
1727361706336,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | FIPS mode is disabled
"
1727361706336,"2024-09-26 14:41:46 UTC | DD_EXTENSION | INFO | 0 Features detected from environment:
"
1727361706336,"2024-09-26 14:41:46 UTC | DD_EXTENSION | INFO | Loaded configuration: /var/task/datadog.yaml
"
1727361706336,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | otlp endpoint disabled
"
1727361706336,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | Enabling telemetry collection HTTP route
"
1727361706336,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | Subscribing to Telemetry for types: [platform function extension]
"
1727361706375,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | Setting DefaultEnv to ""prod"" (from 'env' config option)
"
1727361706436,"TELEMETRY	Name: datadog-agent	State: Already subscribed	Types: [Platform, Function, Extension]
"
1727361706457,"2024-09-26 14:41:46 UTC | DD_EXTENSION | INFO | Starting logs-agent...
"
1727361706458,"2024-09-26 14:41:46 UTC | DD_EXTENSION | INFO | logs-agent started
"
1727361706458,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | Adding AWS Logs Log Source
"
1727361706458,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | Starting ColdStartSpanCreator
"
1727361706458,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | Setting ColdStartSpanCreator on Daemon
"
1727361706458,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | could not list environment variable for proc id %d 1
"
1727361706459,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | finding the lambda runtime took 527.91µs. found runtime: nodejs20.x
"
1727361706495,"2024-09-26 14:41:46 UTC | DD_EXTENSION | DEBUG | serverless agent ready in 601.149168ms
"
1727361708295,"2024-09-26 14:41:48 UTC | DD_EXTENSION | INFO | Container metrics provider discovery process finished
"
1727361709520,"EXTENSION	Name: datadog-agent	State: Ready	Events: [INVOKE, SHUTDOWN]
"
1727361709520,"EXTENSION	Name: AWSParametersAndSecretsLambdaExtension	State: Ready	Events: [SHUTDOWN, INVOKE]
"
1727361709520,"START RequestId: c398b1c8-ce7f-4a67-8155-8092b2f3e125 Version: $LATEST
"
1727361709535,"[AWS Parameters and Secrets Lambda Extension] 2024/09/26 14:41:49 INFO ready to serve traffic
"
1727361709535,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Received invocation event...
"
1727361709535,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Starting Log Collection with ARN: ********************** and RequestId:
"
1727361709535,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | The flush strategy end has decided to not flush at moment: starting
"
1727361709537,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Enhanced metrics: {durationMs:5000 billedDurationMs:5000 memorySizeMB:512 maxMemoryUsedMB:247 initDurationMs:0 initDurationTelemetry:0 initStartTime:{wall:0 ext:0 loc:<nil>}}
"
1727361709538,"2024-09-26T14:41:49.538Z	c398b1c8-ce7f-4a67-8155-8092b2f3e125	DEBUG	{""status"":""debug"",""message"":""datadog:Didn't patch console output with trace context""}
"
1727361709538,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | InitReport done metrics: {durationMs:0 billedDurationMs:0 memorySizeMB:0 maxMemoryUsedMB:0 initDurationMs:0 initDurationTelemetry:4739.407 initStartTime:{wall:0 ext:0 loc:<nil>}}
"
1727361709538,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | [ColdStartCreator] No init duration, passing
"
1727361709538,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | [ColdStartCreator] No lambda span, passing
"
1727361709556,"2024-09-26T14:41:49.556Z	c398b1c8-ce7f-4a67-8155-8092b2f3e125	DEBUG	{""status"":""debug"",""message"":""datadog:Patching HTTP libraries""}
"
1727361709557,"2024-09-26T14:41:49.557Z	c398b1c8-ce7f-4a67-8155-8092b2f3e125	DEBUG	{""status"":""debug"",""message"":""datadog:event.Execution is not an object.""}
"
1727361709558,"2024-09-26T14:41:49.558Z	c398b1c8-ce7f-4a67-8155-8092b2f3e125	DEBUG	{""status"":""debug"",""message"":""datadog:Reading Xray trace context from env var Root=1-66f572a8-78522a671aafb6075eaae733;Parent=3c8322a1922bc13f;Sampled=0;Lineage=1:c0d1eef0:0""}
"
1727361709559,"2024-09-26T14:41:49.559Z	c398b1c8-ce7f-4a67-8155-8092b2f3e125	DEBUG	{""status"":""debug"",""message"":""datadog:Extracted trace context from xray context"",""traceContext"":{""traceId"":""1922955708679776051"",""parentId"":""4360366941562192191"",""sampleMode"":-1,""source"":""xray""}}
"
1727361709559,"2024-09-26T14:41:49.559Z	c398b1c8-ce7f-4a67-8155-8092b2f3e125	DEBUG	{""status"":""debug"",""message"":""datadog:Didn't attempt to find parent for aws.lambda span"",""mergeDatadogXrayTraces"":false,""traceSource"":""xray""}
"
1727361709561,"2024-09-26T14:41:49.561Z	c398b1c8-ce7f-4a67-8155-8092b2f3e125	DEBUG	{""status"":""debug"",""message"":""datadog:Extension present: true""}
"
1727361709561,"2024-09-26T14:41:49.561Z	c398b1c8-ce7f-4a67-8155-8092b2f3e125	DEBUG	{""status"":""debug"",""message"":""datadog:Using StatsD client""}
"
1727361709575,"2024-09-26T14:41:49.575Z	c398b1c8-ce7f-4a67-8155-8092b2f3e125	DEBUG	{""status"":""debug"",""message"":""datadog:Creating the aws.lambda span""}
"
1727361709578,*****REDACTED******
"
1727361709762,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Timeout detected, finishing the current invocation now to allow receiving the SHUTDOWN event
"
1727361709795,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | LogMessage.UnmarshalJSON: no spans object received
"
1727361709795,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Runtime done metrics: {responseLatency:0 responseDuration:0 producedBytes:0}
"
1727361709796,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Received a runtimeDone log message for the current invocation c398b1c8-ce7f-4a67-8155-8092b2f3e125
"
1727361709796,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | The flush strategy end has decided to flush at moment: stopping
"
1727361709800,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Beginning metrics flush at time 1727361709
"
1727361709835,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Received a Flush trigger
"
1727361709837,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : *******REDACTED*******
"
1727361709855,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : *******REDACTED*******
"
1727361709855,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : *******REDACTED*******
"
1727361709855,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : *******REDACTED*******
"
1727361709855,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : *******REDACTED*******
"
1727361709855,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : *******REDACTED*******
"
1727361709855,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : *******REDACTED*******
"
1727361709855,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : *******REDACTED*******
"
1727361709855,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : *******REDACTED*******
"
1727361709855,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : *******REDACTED*******
"
1727361709855,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : *******REDACTED*******
"
1727361709855,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Beginning traces flush at time 1727361709
"
1727361709855,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Finished traces flush that was started at time 1727361709
"
1727361709855,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Beginning logs flush at time 1727361709
"
1727361709855,"2024-09-26 14:41:49 UTC | DD_EXTENSION | INFO | Triggering a flush in the logs-agent
"
1727361709855,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Flush in the logs-agent done.
"
1727361709855,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Finished logs flush that was started at time 1727361709
"
1727361709855,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Demultiplexer: sendIterableSeries: start sending iterable series to the serializer
"
1727361709855,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | The payload was not too big, returning the full payload
"
1727361709855,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | The payload was not too big, returning the full payload
"
1727361709855,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Received shutdown event. Reason: timeout
"
1727361709876,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Send messages for pipeline logs (msg_count:124, content_size=129471, avg_msg_size=1044.12)
"
1727361709949,"2024-09-26 14:41:49 UTC | DD_EXTENSION | INFO | Successfully posted payload to ""https://7-53-0-app.agent.datadoghq.com/api/beta/sketches"" (202 Accepted), the agent will only log transaction success every 500 transactions
"
1727361709949,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | SyncForwarder has flushed 1 transactions
"
1727361709958,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | SyncForwarder has flushed 1 transactions
"
1727361709958,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Demultiplexer: sendIterableSeries: stop routine
"
1727361709959,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Finished metrics flush that was started at time 1727361709
"
1727361709959,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Finished flushing
"
1727361709959,"2024-09-26 14:41:49 UTC | DD_EXTENSION | DEBUG | Waiting to shut down HTTP server
"
1727361710159,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | Shutting down HTTP server
"
1727361710159,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | Beginning metrics flush at time 1727361710
"
1727361710159,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | Received a Flush trigger
"
1727361710160,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | Beginning traces flush at time 1727361710
"
1727361710160,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | Finished traces flush that was started at time 1727361710
"
1727361710160,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : *******REDACTED*******
"
1727361710161,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | Sending sketches payload : *******REDACTED*******
"
1727361710161,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | The payload was not too big, returning the full payload
"
1727361710161,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | Demultiplexer: sendIterableSeries: start sending iterable series to the serializer
"
1727361710161,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | The payload was not too big, returning the full payload
"
1727361710161,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | Beginning logs flush at time 1727361710
"
1727361710161,"2024-09-26 14:41:50 UTC | DD_EXTENSION | INFO | Triggering a flush in the logs-agent
"
1727361710161,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | Flush in the logs-agent done.
"
1727361710161,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | Finished logs flush that was started at time 1727361710
"
1727361710162,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | Send messages for pipeline logs (msg_count:37, content_size=44182, avg_msg_size=1194.11)
"
1727361710179,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | SyncForwarder has flushed 1 transactions
"
1727361710179,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | Demultiplexer: sendIterableSeries: stop routine
"
1727361710179,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | SyncForwarder has flushed 1 transactions
"
1727361710179,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | Finished metrics flush that was started at time 1727361710
"
1727361710179,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | Finished flushing
"
1727361710179,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | Shutting down agents
"
1727361710179,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | [ColdStartCreator] - sending shutdown msg
"
1727361710179,"2024-09-26 14:41:50 UTC | DD_EXTENSION | INFO | Stopping logs-agent
"
1727361710179,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | [ColdStartCreator] - shutting down
"
1727361710227,"2024-09-26 14:41:50 UTC | DD_EXTENSION | INFO | logs-agent stopped
"
1727361710227,"2024-09-26 14:41:50 UTC | DD_EXTENSION | DEBUG | Serverless agent shutdown complete
"
1727361710245,"END RequestId: c398b1c8-ce7f-4a67-8155-8092b2f3e125
"
1727361710245,"REPORT RequestId: c398b1c8-ce7f-4a67-8155-8092b2f3e125	Duration: 5000.00 ms	Billed Duration: 5000 ms	Memory Size: 512 MB	Max Memory Used: 235 MB	Status: timeout
"
```

As you can see, the datadog layer took ~4.6s to initialize, leaving less than 500ms for the actual lambda execution before timeout was reached. This also has a large cost impact on us, since that 4.6s is included in the billed duration. Before adding the datadog layer we were able to run this lambda at 128MB memory, but now it requires 512MB memory to avoid timing out so often that it degrades our service (currently timeouts are < 0.1% of requests with 512MB, but still an issue for us).

**Comment by swcloudgenie** [comment]
Here is a CDK stack that can be used to reproduce the issue: https://github.com/Genie-Garage/datadog-timeout.git

This will have to be run for ~1 hour before seeing timeouts, but we have reproduced this reliably several times now. Is there anyone from the Datadog side that could look into reproducing this?

NOTE: We have reproduced this issue with the "next" beta version as well as the most recent stable version of the extension.

**Comment by duncanista** [comment]
Hey @swcloudgenie, thanks for sending us this example!

I'll take a look at it as soon as possible!

Really appreciate the effort here, will updating as soon as I can

**Comment by duncanista** [comment]
Hey, I'm OOO, will work on this in the following week – sorry for the inconvenience.

**Comment by duncanista** [comment]
Hey, I'm actively working on this, as well as the other new issues in v67, will keep posting.

**Comment by duncanista** [comment]
Hey – as a starting point, I'm using @swcloudgenie's reproduction example.

Yet, I've been unable to see sporadic timeouts so far.

![Image](https://github.com/user-attachments/assets/6f9675de-9f0c-4129-a027-2b6780e33c16)
![Image](https://github.com/user-attachments/assets/d393ca74-cd6b-4c8f-9be6-144cbd7f4b57)
![Image](https://github.com/user-attachments/assets/a249b63c-248a-40df-b238-436165ba0a72)

I'll keep researching into this nonetheless.

This test used my Secret ARN, with 128MB NodeJS 20 AWS Lambdas. I used v63, v63-next, and v67-next so far.

I might need more insights on how long should I let this run (I only did sub 1 hour).

If you have an on-going ticket with us at Datadog, feel free to mention me (Jordan González from the Serverless AWS team) to take a look at your case.

I'll keep updating if I'm able to reproduce it, I'd appreciate more insights.

**Comment by swcloudgenie** [comment]
@duncanista in my testing, I needed at least 30 minutes, and sometimes over an hour to reproduce. Also, you need to use the AWS console to look for timeouts. The timeouts will not reach Datadog, since the Datadog layer itself is timing out trying to set itself up. This is not always the case, but in our testing so far we often do not receive metrics/logs for the timeouts in Datadog, we have to rely on CloudWatch in the AWS console.

**Comment by astuyve** [comment]
Hey folks!

We've followed up with @swcloudgenie and confirmed this issue is related to a recent change made by AWS to reduce the available vCPU resources and enforce the function timeout during a suppressed initialization. I've called it the [doom loop](https://aaronstuyvenberg.com/posts/lambda-timeout-doom-loop).

Here's a brief summary:
During the normal initialization phase of a Lambda function, AWS boosts the amount of CPU resources to 1vCPU, equivalent to setting the function configuration to 1769mb RAM as documented [here](https://docs.aws.amazon.com/lambda/latest/dg/configuration-memory.html). Additionally, the initialization timeout is set to 10 seconds regardless of the function timeout setting.

This gives your function extra time to decrypt secrets from secrets manager (which must happen in this case), start the extension process, start the nodejs process, load all the dependencies from S3, and wait for the extension and function to call the /next endpoint indicating that they are ready to process requests.

That function can now happily process requests for several minutes or hours.

But say that eventually the function crashes the process, times out, or throws an unhandled exception - now Lambda has to re-initialize the process. This is called a `suppressed init` in the AWS documentation.

So the runtime process has to restart. The entire cold start process begins. If you're using Secrets Manager, that key must be re-fetched, v4 signatures must be recomputed, lambda must load all your code dependencies and initialize them, etc.

Now that AWS Lambda has made a new change which enforces the function global timeout (in our example case here, 3s) along with the limited vCPU set by the RAM setting (in this case 1/8th vCPU or 128mb RAM).

For functions with short timeouts and low amounts of RAM, this stretches the cold start much much longer than a normal initialization! A function which initializes in 1.5s normally may take 8+ seconds when it has 1/8th of the vCPU power available.

Coupled with a low timeout which is now enforced during the re-initialization, the function may fail to initialize over and over again – until Lambda reaps the function and restarts it from scratch. I’d fully expect that this demo case provided by the user above, when coupled with a few lambda dependencies and some actual business logic, could cause the function to timeout indefinitely.

This is what occurred in [this invocation](https://github.com/DataDog/datadog-lambda-extension/issues/191#issuecomment-2377892734).

This is the doom loop.

Now to address the timeout while flushing data:
Today, flushing data back to Datadog occurs after the lambda function already returns to the user – but the time taken for this extension to send data back to Datadog still counts as function duration time. We're working on a new change to observe and postpone/abort data flushing as we approach the configured function timeout, to prevent the sandbox from encountering a suppressed init. We're also working on reducing the size and impact of Datadog's instrumentation on customer runtimes, including this project which, over the course of this 1 year old issue, seems to have averted this issue entirely.

To avoid encountering a doom loop or suppressed init, we recommend reducing the code loaded by functions to a minimum, increasing configured RAM, and increasing the timeout value (as it governs the entire sandbox lifecycle, and not strictly the SLA for your function to return its response to the calling user).

I'll close this for now, if you're still encountering issues, please feel free to share detailed reports and debug logs – the fastest way to do that securely is by opening a bug ticket with us via `support@datadoghq.com`.

If you have any questions or concerns you can always reach out to me directly at aj@datadoghq.com
Thanks!
AJ

**Comment by astuyve** [comment]
Hey @efimk-me - it's not documented but it's provable, you can still measure it following Michael Hart's example https://hichaelmart.medium.com/shave-99-93-off-your-lambda-bill-with-this-one-weird-trick-33c0acebb2ea
