### ISSUE TITLE
Datadog Lambda Extension v61 causes lambdas to crash on startup

### ISSUE THREAD

**Issue by JavaScriptBach** [DataDog/datadog-lambda-extension#331]
The latest version of the Datadog Lambda Extension (v61) causes my lambdas to crash on startup with the error `UnsupportedField("extension_version")`.

I am running Node.js lambdas using the AWS Node 20 base container image in x86. I'm guessing https://github.com/DataDog/datadog-lambda-extension/pull/328 is related?

**Comment by DylanLovesCoffee** [comment]
hey @JavaScriptBach - apologies for this. We're working on reproducing and fixing the issue at the moment.

**Comment by JavaScriptBach** [comment]
Thanks! In the meantime, my lambdas are working again on v60.

Some more context in case it helps:

- My Dockerfile base image looks like this:
```
FROM public.ecr.aws/lambda/nodejs:20.2024.05.08.11-x86_64
COPY --from=public.ecr.aws/datadog/lambda-extension:latest /opt/extensions/ /opt/extensions
```

- I'm using the `datadog-lambda-js` library version 7.104.0.
- My lambda's DD_ env variables are `DD_API_KEY_SECRET_ARN`, `DD_ENV`, `DD_SERVICE`, `DD_SITE`, and `DD_VERSION`.
- And my Cloudwatch logs look like this:

```

2024-07-23T01:01:25.388Z{     "DD_EXTENSION_FAILOVER_REASON": "extension_version" } | {"DD_EXTENSION_FAILOVER_REASON":"extension_version"}
-- | --
  | 2024-07-23T01:01:25.396ZError loading configuration: UnsupportedField("extension_version") | Error loading configuration: UnsupportedField("extension_version")
  | 2024-07-23T01:01:25.399ZEXTENSION	Name: datadog-agent	State: Started	Events: [] | EXTENSION Name: datadog-agent State: Started Events: []
  | 2024-07-23T01:01:25.399ZEXTENSION	Name: datadog-agent-go	State: Started	Events: [] | EXTENSION Name: datadog-agent-go State: Started Events: []
  | 2024-07-23T01:01:25.399ZINIT_REPORT Init Duration: 103.79 ms	Phase: init	Status: error	Error Type: Extension.Crash | INIT_REPORT Init Duration: 103.79 ms Phase: init Status: error Error Type: Extension.Crash
  | 2024-07-23T01:01:25.419Z{     "DD_EXTENSION_FAILOVER_REASON": "extension_version" } | {"DD_EXTENSION_FAILOVER_REASON":"extension_version"}
  | 2024-07-23T01:01:25.420ZError loading configuration: UnsupportedField("extension_version") | Error loading configuration: UnsupportedField("extension_version")
  | 2024-07-23T01:01:25.429ZEXTENSION	Name: datadog-agent	State: Started	Events: [] | EXTENSION Name: datadog-agent State: Started Events: []
  | 2024-07-23T01:01:25.429ZEXTENSION	Name: datadog-agent-go	State: Started	Events: [] | EXTENSION Name: datadog-agent-go State: Started Events: []
  | 2024-07-23T01:01:25.429ZINIT_REPORT Init Duration: 11.48 ms	Phase: invoke	Status: error	Error Type: Extension.Crash | INIT_REPORT Init Duration: 11.48 ms Phase: invoke Status: error Error Type: Extension.Crash
  | 2024-07-23T01:01:25.429ZSTART RequestId: a0d24255-c1c3-4f97-8efb-daee86bab6cd Version: $LATEST | START RequestId: a0d24255-c1c3-4f97-8efb-daee86bab6cd Version: $LATEST
  | 2024-07-23T01:01:25.439ZRequestId: a0d24255-c1c3-4f97-8efb-daee86bab6cd Error: signal: illegal instructionExtension.Crash | RequestId: a0d24255-c1c3-4f97-8efb-daee86bab6cd Error: signal: illegal instruction Extension.Crash
  | 2024-07-23T01:01:25.439ZEND RequestId: a0d24255-c1c3-4f97-8efb-daee86bab6cd | END RequestId: a0d24255-c1c3-4f97-8efb-daee86bab6cd
  | 2024-07-23T01:01:25.439ZREPORT RequestId: a0d24255-c1c3-4f97-8efb-daee86bab6cd	Duration: 20.34 ms	Billed Duration: 21 ms	Memory Size: 2048 MB	Max Memory Used: 6 MB

```

**Comment by DylanLovesCoffee** [comment]
Thanks for the additional details, Phillip! At the moment this seems isolated to the container images, so we're working to address that.

**Comment by benconnito** [comment]
v61 lambda extension (as a layer ... not container) seems to report the agent version as `6.0.0`

![image](https://github.com/user-attachments/assets/70cbf23f-aa50-44a1-b2ec-cd9c00885628)

**Comment by ItayVortex** [comment]
how do you change the version in container lambdas? it crash our production right now

**Comment by loicgasser** [comment]
@ItayVortex I am using `COPY --from=public.ecr.aws/datadog/lambda-extension:60 /opt/extensions/ /opt/extensions`

**Comment by loicgasser** [comment]
If that's of any help:

python 3.10 in docker

```
2024-07-23T07:19:34.217-04:00	REPORT RequestId: 407e9068-a29f-4879-8c5f-cc48667e94df Duration: 102.01 ms Billed Duration: 103 ms Memory Size: 128 MB Max Memory Used: 4 MB
2024-07-23T07:19:35.575-04:00	{"DD_EXTENSION_FAILOVER_REASON":"extension_version"}
2024-07-23T07:19:35.616-04:00	EXTENSION Name: datadog-agent State: Started Events: []
2024-07-23T07:19:35.616-04:00	INIT_REPORT Init Duration: 71.49 ms Phase: invoke Status: error Error Type: Extension.Crash
2024-07-23T07:19:35.616-04:00	START RequestId: 2695339c-402b-47c1-ae35-abb35deee72b Version: $LATEST
2024-07-23T07:19:35.617-04:00	RequestId: 2695339c-402b-47c1-ae35-abb35deee72b Error: signal: illegal instruction Extension.Crash
2024-07-23T07:19:35.617-04:00	END RequestId: 2695339c-402b-47c1-ae35-abb35deee72b
```

Using lambda as a docker container and I am invoking it.

**Comment by AdamHess** [comment]
@loicgasser   I was able to resolve things on my end by switching it to `/opts/.  /opts/`

**Comment by vin** [comment]
Can you paste in SHAs of the fixed images? We tried rebuilding with `public.ecr.aws/datadog/lambda-extension:latest` and still seeing the same issue

**Comment by vin** [comment]
FWIW in my app's container image I see:
```
bash-4.2# /opt/extensions/datadog-agent 
Illegal instruction (core dumped)
bash-4.2# /opt/extensions/datadog-agent --version
Illegal instruction (core dumped)
bash-4.2# md5sum /opt/extensions/datadog-agent 
f800838aeb6a060993901a144f8575bb  /opt/extensions/datadog-agent
bash-4.2# exit
```

```
vscode@codespaces-f55ca6:/workspaces/docr$ docker pull public.ecr.aws/datadog/lambda-extension:latest
latest: Pulling from datadog/lambda-extension
Digest: sha256:1de975fe9e9aaec605985c1786d994807f16d0eebdfd55facd26d48d5f9106e4
Status: Image is up to date for public.ecr.aws/datadog/lambda-extension:latest
public.ecr.aws/datadog/lambda-extension:latest
```

**Comment by konstista** [comment]
We are facing this issue as well, some deployments are not functional right now. Thanks for looking into that.

**Comment by wesleyjin** [comment]
Our team is also running into this issue with our Python container images. 
`sam deploy` fails in CI/CD because of our Lambda provisioned concurrency config.

Commenting for discoverability

```txt
# CloudFormation.ResourceStatusReason error log
Provisioned Concurrency configuration failed to be applied. Reason: FAILED" (RequestToken: {uuid-here}, HandlerErrorCode: NotStabilized)
```


```Dockerfile
# Dockerfile
FROM public.ecr.aws/lambda/python:3.9 AS runtime-image
...
COPY --from=public.ecr.aws/datadog/lambda-extension:latest /opt/extensions/ /opt/extensions
```

```txt
# Cloudwatch Log Stream
INIT_REPORT Init Duration: 64.25 ms Phase: init Status: error Error Type: Extension.Crash
EXTENSION Name: datadog-agent State: Started Events: []
{"DD_EXTENSION_FAILOVER_REASON":"extension_version"}
```

**Comment by vin** [comment]
We've tried using public.ecr.aws/datadog/lambda-extension:60 instead. It doesn't crash, but it does have some other errors showing up in the logs. At least our lambda is running for the time being, not sure whether our telemetry is being recorded (doubtful).

**Comment by vin** [comment]
Is it possible to roll back to the last known-good version? How can we escalate this issue?

**Comment by duncanista** [comment]
Here are the SHAs for the images that should not have any issues:

# ECR
`latest-alpine`
- `amd64`: `036faf17cb8d40f3c0a655b422d0a2f7d0227ca0c2c4dbde5c2026a18f2510ab`
- `arm64`: `a381dac1c02973a30136b5624495b07986ae40a568fbf8299b7880efd73f130b`

`latest`
- `amd64`: `09e212d515a7466e1134dc900811b7170cdcdc981fe7693a1e5c2fce6d3ec00c`
- `arm64`: `9826624788ce4563e464f21c2b3da72c41ec73efbb072d53ea7089ce14a5d0a8`

`61-alpine`
- `amd64`: `036faf17cb8d40f3c0a655b422d0a2f7d0227ca0c2c4dbde5c2026a18f2510ab` (same as `latest`)
- `arm64`: `a381dac1c02973a30136b5624495b07986ae40a568fbf8299b7880efd73f130b` (same as `latest`)

`61`
- `amd64`: `09e212d515a7466e1134dc900811b7170cdcdc981fe7693a1e5c2fce6d3ec00c` (same as `latest`)
- `arm64`: `9826624788ce4563e464f21c2b3da72c41ec73efbb072d53ea7089ce14a5d0a8` (same as `latest`)


Will add more comments for other registries. I manually checked the images and ran some containerized Lambdas to ensure their proper execution.

I'll take the feedback and share it with my team, this issue is not happening for Lambda Layers, this is confirmed.

**Comment by duncanista** [comment]
After a discussion with my team and reading all your valuable feedback, we will release a new version so no caches need to be cleared from your side. I understand the frustration and how critical this is. Please rest assure our team is working non-stop to find the best solution for this. Although our remediation looked like it fixed it, other external factors might come into play – cached images for example.

Thanks for understanding, and will keep updating.

**Comment by duncanista** [comment]
Hey @loicgasser 

> @ItayVortex I am using COPY --from=public.ecr.aws/datadog/lambda-extension:60 /opt/extensions/ /opt/extensions

The [docs](https://docs.datadoghq.com/serverless/aws_lambda/installation/python/?tab=containerimage) recommend doing:

```
COPY --from=public.ecr.aws/datadog/lambda-extension:<TAG> /opt/. /opt/
```

Let me know if that fixes your issue!

**Comment by duncanista** [comment]
Hey @vin,

Just wanted to check if you were copying the full `/opt/` or just `/opt/extensions`?

**Comment by dali546** [comment]
Hi @duncanista, we also just experienced this issue when using v61. We were already copying the entire `/opt`
```
COPY --from=public.ecr.aws/datadog/lambda-extension:61-alpine /opt/ /opt/
```
The error we received was:
> fork/exec /opt/extensions/datadog-agent: no such file or directory
Extension.LaunchError

**Comment by wesleyjin** [comment]
> @wesleyjin
> 
> > COPY --from=public.ecr.aws/datadog/lambda-extension:latest /opt/extensions/ /opt/extensions
> 
> The [docs](https://docs.datadoghq.com/serverless/aws_lambda/installation/python/?tab=containerimage) recommend doing:
> 
> ```
> COPY --from=public.ecr.aws/datadog/lambda-extension:<TAG> /opt/. /opt/
> ```
> 
> This change has been out for a while (since our ASM integration required changing how layer is copied!)
> 
> Let me know if that fixes your issue!

@duncanista thanks! that worked:

We're now using:
```Dockerfile
...
COPY --from=public.ecr.aws/datadog/lambda-extension:latest /opt/. /opt/
...
```

**Comment by duncanista** [comment]
Hey @dali546,

Yeah – sorry for this, it seems this is indeed the faulty version sha, I already talked with the internal team in charge of public images so we can yank that sha hopefully 🙇🏽 .

And at the same time, we might release a new version soon just to remove some messages from our Rust extension which might cause confusion with customers

**Comment by vin** [comment]
Thanks for pointing out the installation instructions change. I see that now and we'll try it. I had a locally-built container image where I had tried copying all of /opt, but invoking /opt/extensions/datadog-agent still died with `Illegal instruction (core dumped)`. To be clear, that was running locally with `docker run -it --entrypoint /bin/bash ...`. I didn't try that on the lambda runtime.

We'll try that now with v61 and report back. Thanks.

**Comment by vin** [comment]
ok :61 does seem to be not crashing, while also using
```
COPY --from=public.ecr.aws/datadog/lambda-extension:latest /opt/. /opt/
```

interactively I still see
```
bash-4.2# /opt/extensions/datadog-agent 
Illegal instruction (core dumped)
```

which is a bit disconcerting, but I guess it doesn't have diagnostic value.

So our service is at least running, but now we're seeing some (probably unrelated) stack trace in our logs and not successfully reporting telemetry, but at least our service is up!

**Comment by rhinoceraptor** [comment]
I'm still getting the following error:

```
2024-07-24 13:33:51 UTC | DD_EXTENSION | ERROR | Can't init UDS listener on path /var/run/datadog/dsd.socket: can't listen: listen unixgram /var/run/datadog/dsd.socket: bind: no such file or directory
```

My `Dockerfile` has the following:
```Dockerfile
FROM public.ecr.aws/lambda/python:3.8

WORKDIR ${LAMBDA_TASK_ROOT}

COPY --from=public.ecr.aws/datadog/lambda-extension:latest /opt/. /opt/
```

I have in my `requirements.txt`
```
datadog-lambda==6.97.0
ddtrace==2.9.3
```

It doesn't crash, but I'm not sure if it's an issue or not.

**Comment by duncanista** [comment]
Hey, thanks for the heads up, I continue working on this to now investigate the `Can't init UDS listener on path...`

**Comment by duncanista** [comment]
This 
```
2024-07-24 13:33:51 UTC | DD_EXTENSION | ERROR | Can't init UDS listener on path /var/run/datadog/dsd.socket: can't listen: listen unixgram /var/run/datadog/dsd.socket: bind: no such file or directory
```

Seems to be unrelated to the changes made in this repository, this is an upstream bug coming from Datadog Agent, will work with the team to figure this one out.

**Comment by duncanista** [comment]
On the previous mentioned error, we have checked that this will not cause any data loss, it's benign. Yet, something we should definitely update. Will keep posting.

**Comment by eslamodeh** [comment]
Had similar issues

Switch to use `public.ecr.aws/datadog/lambda-extension:60` instead of `public.ecr.aws/datadog/lambda-extension:latest`

**Comment by duncanista** [comment]
Hey everyone,

### We have released `v62` addressing a couple of concerns raised in this issue:

1. On `UDS listener...` error log:
```
2024-07-24 13:33:51 UTC | DD_EXTENSION | ERROR | Can't init UDS listener on path /var/run/datadog/dsd.socket: can't listen: listen unixgram /var/run/datadog/dsd.socket: bind: no such file or directory
```

This was a breaking change made on the Datadog Agent, we have updated it so it's different for serverless environments. Totally benign, but clearly confusing. It shouldn't be present anymore.

2. On `Error loading configuration` error log:
```
2024-07-23T01:01:25.396ZError loading configuration: UnsupportedField("extension_version") | Error loading configuration: UnsupportedField("extension_version")
```

We forgot to remove this from our newest Rust build, this was confusing from a customer point of view. It was also benign, but we've removed our approach with this.

3. Extension reporting as Agent version `6.0.0`:

An issue on our automated pipeline avoided tagging with the right agent version, this has been addressed and solved.

4. On the container image crashing environments:

This incident was resolved within a few hours, but we know that some customers cached images still had this issue. We are unable to remove the previous sha containing this faulty image, so we decided to release a new version for it.


On another note, you might see a log like:
```
2024-07-23T07:19:35.575-04:00	{"DD_EXTENSION_FAILOVER_REASON":"XXXX"}
```
This is an internal metric from our Rust build, feel free to ignore it. If this presents a problem for you, please let us know and we will figure a better way to gather this metric. This metric will never be included in your bill.

---
Again, we are very sorry for the inconvenience, we value your feedback and continued support. I'm going to close this issue and mark it as resolved tomorrow, so feel free to ask any questions or concerns if any.

**Comment by duncanista** [comment]
Closing this issue.

Make sure to please update to `v62`, `latest` for container images has been updated to that version too.
Also, please ensure to update your instrumentation in container images as the following:

```
COPY --from=public.ecr.aws/datadog/lambda-extension:<TAG> /opt/. /opt/
```

Feel free to re-open if there's any more concerns/questions around this. 

Thanks everyone!

**Comment by leonardobsjr** [comment]
I still have this issue when trying to execute the Lambda function locally via the API:
`curl -vvvk -X POST -d '{}' -vvvk http://localhost:8080/2015-03-31/functions/function/invocations`

Gives me a 502 and logs indicate the illegal instruction error:
`29 Jul 2024 17:15:43,020 [INFO] (rapid) exec '/var/runtime/bootstrap' (cwd=/var/task, handler=)
START RequestId: d2f0a684-9912-4148-81fb-6bef92a18171 Version: $LATEST
29 Jul 2024 17:16:02,870 [INFO] (rapid) INIT START(type: on-demand, phase: init)
29 Jul 2024 17:16:02,876 [WARNING] (rapid) First fatal error stored in appctx: Extension.Crash
29 Jul 2024 17:16:02,876 [WARNING] (rapid) Process extension-datadog-agent-1 exited: signal: illegal instruction`

**Comment by duncanista** [comment]
Hey @leonardobsjr, could you share more details about how you're testing it locally? As in the configuration for this?

**Comment by astuyve** [comment]
Hi @leonardobsjr et al, it looks like the runtime interface emulator doesn't set some [expected env vars](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html), including `AWS_DEFAULT_REGION`.

If you add that, the error should disappear. We'll release a fix to remove that `expect` clause.

**Comment by leonardobsjr** [comment]
Thanks for the follow up @astuyve! Yeah, I was able to identify this, but the biggest issue is that the behavior suddenly changed from v60.  On v60 the /opt/extensions/datadog-agent started just fine, while on v61+ it fails. The side-effect is that, on v60, even without the vars, you could get a successful response, while on v61 you get a 502, which breaks our tests. 

Weirdly the code where the apparently expects lie (https://github.com/DataDog/datadog-lambda-extension/blob/main/bottlecap/src/bin/bottlecap/main.rs#L193-L199) seems to not have changed from v60. Setting up those exact variables make the v62 behavior like before. 

That's what I used to verify:
index.js:
```
const { sendDistributionMetric, sendDistributionMetricWithDate } = require('datadog-lambda-js');
const tracer = require('dd-trace');

// submit a custom span named "sleep"
const sleep = tracer.wrap('sleep', (ms) => {
    return new Promise((resolve) => setTimeout(resolve, ms));
});

exports.handler = async (event) => {
    // add custom tags to the lambda function span,
    // does NOT work when X-Ray tracing is enabled
    const span = tracer.scope().active();
    span.setTag('customer_id', '123456');

    await sleep(100);

    // submit a custom span
    const sandwich = tracer.trace('hello.world', () => {
        console.log('Hello, World!');
    });

    // submit a custom metric
    sendDistributionMetric(
        'coffee_house.order_value', // metric name
        12.45, // metric value
        'product:latte', // tag
        'order:online' // another tag
    );

    const response = {
        statusCode: 200,
        body: JSON.stringify('Hello from serverless!')
    };
    return response;
};
```
Dockerfile.test
```
FROM public.ecr.aws/lambda/nodejs:20 as builder

COPY . ${LAMBDA_TASK_ROOT}
RUN npm install datadog-lambda-js dd-trace

COPY --from=public.ecr.aws/datadog/lambda-extension:62 /opt/. /opt/

ENV DD_LAMBDA_HANDLER="index.handler"

CMD ["node_modules/datadog-lambda-js/dist/handler.handler"]
#CMD ["index.handler"]
```

And later calling locally:
`docker build --pull --no-cache -f Dockerfile.test -t test . ; docker run -d --name lambda-example -p 9001:8080 test ; curl -vvvk "http://localhost:9001/2015-03-31/functions/functio
n/invocations" -d '{"payload":"hello world!"}'

**Comment by duncanista** [comment]
Hey, for more context on

> Weirdly the code where the apparently expects lie (https://github.com/DataDog/datadog-lambda-extension/blob/main/bottlecap/src/bin/bottlecap/main.rs#L193-L199) seems to not have changed from v60. Setting up those exact variables make the v62 behavior like before.

v60 doesn't include any of the Rust code yet.

Thanks for providing your testing example, we'll be working on fixing this, sorry for the inconvenience!

**Comment by duncanista** [comment]
Hey @leonardobsjr,

This should be fixed on [v63](https://github.com/DataDog/datadog-lambda-extension/releases/tag/v63), let us know if you have any issues!
