### ISSUE TITLE
Excessive warn logs after upgrade to v67

### ISSUE THREAD

**Issue by Fodoj** [DataDog/datadog-lambda-extension#496]
After ugprading to v67 and new generation extension, we are getting massive amounts of warn logs like this:

```
{"message":"Successfully buffered traces to be flushed."} while sending 1 (size=2KB) traces. Total: 22, Received: 22, Sent: 0, Failed: 22. Status: 202 Accepted (Will not log warnings for 5 minutes)
```

Disabling next gen exception fixes the problem, but we'd like to avoid disabling it.

**Comment by duncanista** [comment]
Hey @Fodoj

Mmmm interesting, this should be disabled by default, this log is from an upstream dependency. Could you share a little bit more context of your setup? So we can research on reproducing it?

**Comment by Fodoj** [comment]
It's a Java Lambda service, dd-trace-java v15, dd extension v67, following DD Envs are set:

```
DD_AGENT_HOST | localhost
DD_CAPTURE_LAMBDA_PAYLOAD | false
DD_ENV | dev
DD_EXTENSION_VERSION | compatibility
DD_LOGS_INJECTION | false
DD_LOG_LEVEL | warn
DD_MERGE_XRAY_TRACES | false
DD_RUNTIME_METRICS_ENABLED | false
DD_SERVERLESS_LOGS_ENABLED | true
DD_SERVICE | xxxx
DD_SITE | datadoghq.eu
DD_TRACE_ENABLED | true
DD_TRACE_SAMPLE_RATE | 1.0
```

**Comment by duncanista** [comment]
Yes, as it's using the method `log_and_create_http_response` which exists in https://github.com/DataDog/libdatadog/blob/373b7783730a8191bfb6a1f0135791782cdcc22d/trace-mini-agent/src/http_utils.rs#L21-L26

Which we disable in:
https://github.com/DataDog/datadog-lambda-extension/blob/36396c7cc9670d3bd438abad06928c29e1e8e2fb/bottlecap/src/bin/bottlecap/main.rs#L219-L224

**Comment by duncanista** [comment]
Thanks for sharing more information – I'll look more into this!

**Comment by duncanista** [comment]
This will be fixed in the next version

**Comment by Fodoj** [comment]
@duncanista do you know roughly when new version is going to be released?

**Comment by duncanista** [comment]
@Fodoj yes, I'm hoping to release today, or tomorrow!

**Comment by duncanista** [comment]
This should have been fixed now in [v68](https://github.com/DataDog/datadog-lambda-extension/releases/tag/v68), feel free to re-open if there's any other issues!

**Comment by Fodoj** [comment]
@duncanista I don't have permissions to re-open the issue, but the issue still occurs with version 68 (java agent 15)
