### ISSUE TITLE
Image version 69+ - Error in logs: "invalid compression set"

### ISSUE THREAD

**Issue by credpath-seek** [DataDog/datadog-lambda-extension#566]
Since lambda image 69 we get the following log warning on startup:

```
DD_EXTENSION | ERROR | invalid compression set
```

I rolled back to version 68 and no longer see the error.

I believe the error is related to the agent changes made in this PR:
https://github.com/DataDog/datadog-agent/pull/27148

https://github.com/DataDog/datadog-agent/blob/7b722a315a84db8b0ccdbc1d8300df192c61fddb/pkg/util/compression/selector/zlib-and-zstd.go#L37-L38

Possibly the log message should be made a WARN rather than ERROR, or  perhaps the lambda image should explicitly set the compression kind on the agent to "none"

**Comment by astuyve** [comment]
Fix will be out in v71, thanks!

**Comment by rd-joni** [comment]
Still exists in v72

**Comment by astuyve** [comment]
hey! We had to revert v71 as it caused an issue with enhanced metrics. This should be resolved in v73.

Thanks!

**Comment by astuyve** [comment]
Should be out in [v73]([v73 is OUT](https://github.com/DataDog/datadog-lambda-extension/releases/tag/v73))

**Comment by rd-joni** [comment]
Still happening, different errors
<img width="1296" alt="Image" src="https://github.com/user-attachments/assets/59da918b-f9ab-4e2f-ae06-ee8cf2ce4167" />

**Comment by astuyve** [comment]
hi @rd-joni - That's a separate issue we're tracking [here](https://github.com/DataDog/datadog-lambda-extension/issues/595)
